config/routes.rb
OnlineTest::Application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  devise_for :users

  root :to => 'homes#index'
  resources :homes, :only => [:index]
  resources :questions do
    collection do
      get 'choices'
    end
  end
  resources :answers
  resources :categories
  resources :quizzes do
    collection do
      get 'index'
      get 'question'
      get 'finish'
      get 'start'
      post 'start'
      post 'question'
      post 'exam'
      get 'finish_exam'
      post 'check_descriptive_answers'
      get 'question_back_button'
    end
    member do
      get 'start'
    end
  end

  resources :descriptives
  match '/admin/questions/choices' =>  'admin/questions#questions_choices',  :via => 'post', :as => :admin_question_type_choices

end

app/models/question.rb
class Question < ActiveRecord::Base
  attr_accessible :name, :category_id, :option_type, :answer_attributes, :quiz_id
  belongs_to :category
  has_one :answer
  belongs_to :quiz
  has_one :descriptive
  accepts_nested_attributes_for :answer
  OPTIONS = {'single_choice' => 0, 'multiple_choice' => 1, 'descriptive' => 2}
  #validates :name, :category_id, :option_type, presence: true
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
	def index
    #@category_question = Category.all.collect{|a| [a.question_category, a.id]}
		@questions = Question.all
	end
	def new
		@question = Question.new
	end
	def show
    #@category = Category.find(params[:id])
		@question = Question.find(params[:id])
	end
	def edit
		@question = Question.find(params[:id])
	end
	def create
    @category = Category.find(params[:question][:category_id])
    @question = @category.questions.build(params[:question])
    if @question.option_type == 0
      answer_attributes = [params[:A], params[:B], params[:C], params[:D]]
      @question.build_answer(:question_answer => answer_attributes, :correct_answer => [params[:right_answer]])
    elsif @question.option_type == 1
      answer_attributes = [params[:A], params[:B], params[:C], params[:D]]
      @question.build_answer(:question_answer => answer_attributes, :correct_answer => [params[:correct_multiple_answers]])
    else
      answer_attributes = [params[:write_answer]]
      @question.build_answer(:question_answer => answer_attributes)
    end
    respond_to do |format|
      if @question.save
        format.html { redirect_to @question, notice: 'Question was successfully created.' }
        format.json { render json: @question, status: :created, location: @question }
      else
        format.html { render action: "new" }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end
  def update
    @question = Question.find(params[:id])

    respond_to do |format|
      if @question.update_attributes(params[:question])
        format.html { redirect_to @question, notice: 'Question was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end
  def destroy
    @question = Question.find(params[:id])
    @question.destroy

    respond_to do |format|
      format.html { redirect_to questions_url }
      format.json { head :no_content }
    end
  end
  def choices
    @option = params[:option]
    respond_to do |format|
      format.js
    end
  end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/_descriptive_choice.html.haml
%h4 Decriptive Answer
%div
  = label_tag :write_answer
  = text_area_tag :write_answer

app/views/questions/_form.html.haml
.login_page
  .container
    .question_form
      %h2 Question Form
      = form_for @question do |f|
        - if @question.errors.any?
          #error_explanation
            %h2
              = pluralize(@question.errors.count, "error")
              prohibited this question from being saved:
            %ul
              - @question.errors.full_messages.each do |msg|
                %li= msg
        %div
          = f.label :category
          = f.select :category_id, Category.all.collect{|a| [a.question_category, a.id]}, :prompt => "please select category"
        %div
          = f.label :question_name
          = f.text_area :name, :rows => 3
        %div
          = f.label :option_type
          = f.select :option_type, Answer::OPTIONS.collect{|k, v| [v, k]}, :prompt => "please select option"
        #single_choice
          = #render :partial => "single_choice"
        #multiple_choice
          = #render :partial => "multiple_choice"
        #descriptive_choice
          =# render :partial => "descriptive_choice"
        #please_select_choice
          %br
        %div{:style => "text-align:center;"}
          = f.submit "Create Question", :class => "btn btn-primary"
:javascript
$(document).ready(function(){
  $("#question_option_type").on('change', function(){
    var option_value = $(this).val();
    $.ajax({url: "/questions/choices", 
            data: 'option='+option_value
            });
  });
});

app/views/questions/_multiple_choice.html.haml
%h4 Multiple Answers
%div
  = label_tag :A
  = text_field_tag :A
%div
  = label_tag :B
  = text_field_tag :B
%div
  = label_tag :C
  = text_field_tag :C
%div
  = label_tag :D
  = text_field_tag :D
.form_row
  %label{for: "correct_multiple_answers"} Correct Answers:
  - [ 'A', 'B', 'C', 'D'].each do |correct_multiple_answers|
    = check_box_tag 'correct_multiple_answers', correct_multiple_answers, @correct_multiple_answers == correct_multiple_answers
    = correct_multiple_answers.humanize

app/views/questions/_please_select_choice.html.haml
%h2 Please select any choice

app/views/questions/_single_choice.html.haml
%h4 Single Answers
%div
  = label_tag :A
  = text_field_tag :A
%div
  = label_tag :B
  = text_field_tag :B
%div
  = label_tag :C
  = text_field_tag :C
%div
  = label_tag :D
  = text_field_tag :D
.form_row
  %label{for: "right_answer"} Correct Answer:
  - ['A', 'B', 'C', 'D'].each do |right_answer|
    = radio_button_tag 'right_answer', right_answer, @right_answer == right_answer
    = right_answer.humanize

app/views/questions/choices.js.haml
-if @option == 'single_choice'
  :plain
    $("#single_choice").html("")
    $("#single_choice").html("#{escape_javascript(render(:partial => "single_choice"))}");
-elsif @option == 'multiple_choice'
  :plain
    $("#single_choice").html("")
    $("#single_choice").html("#{escape_javascript( render :partial => "multiple_choice")}");
-elsif @option == 'descriptive'
  :plain
    $("#single_choice").html("")
    $("#single_choice").html("#{escape_javascript( render :partial => "descriptive_choice")}");
-else
  :plain
    $("#single_choice").html("")
    $("#single_choice").html("#{escape_javascript( render :partial => "please_select_choice")}");

app/views/questions/edit.html.haml
= render :partial => "form"

app/views/questions/index.html.haml
.login_page
  .container
    .question_form
      - @questions.each do |question|
        %tr
          %td= "#{question.name}".html_safe
          
          - if Answer::OPTIONS.key(question.option_type) == 'single_choice'
            = form_tag questions_path, :mehtod => 'post' do
              %li
                = radio_button_tag :A, "A"
                = question.answer.A
              %li
                = radio_button_tag :B, "B"
                = question.answer.B
              %li
                = radio_button_tag :C, "C"
                = question.answer.C
              %li
                = radio_button_tag :D, "D"
                = question.answer.D
          - elsif Answer::OPTIONS.key(question.option_type) == 'multiple_choice'
            = form_tag questions_path, :mehtod => 'post' do
              %li
                = check_box_tag :A
                = question.answer.A
              %li
                = check_box_tag :B
                = question.answer.B
              %li
                = check_box_tag :C
                = question.answer.C
              %li
                = check_box_tag :D
                = question.answer.D
                
          - else
            = form_tag questions_path, :mehtod => 'post' do
              = text_area_tag :write_your_answer_here
          %td=# Category.find_by_id(question.category_id).question_category
          %td=# link_to 'Show', question, :class => "btn btn-primary"
          %td=# link_to 'Edit', edit_question_path(question), :class => "btn btn-primary"
          %td= #link_to 'Destroy', question, method: :delete, data: { confirm: 'Are you sure?' }, :class => "btn btn-primary"
  %br/
  =# link_to "Add Question", new_question_path, :class => "btn btn-default"

app/views/questions/show.html.haml
%p
  %b Category :
  = #@category.question_category
%p
  %b Name :
  = @question.name.html_safe
%p
  %b Question Type :
  = "#{@question.option_type}".humanize
= link_to "All Questions", questions_path, :class => "btn btn-primary"
= link_to "Add Category", new_category_path