config/routes.rb
OnlineTest::Application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  devise_for :users

  root :to => 'homes#index'
  resources :homes, :only => [:index]
  resources :questions do
    collection do
      get 'choices'
    end
  end
  resources :answers
  resources :categories
  resources :quizzes do
    collection do
      get 'index'
      get 'question'
      get 'finish'
      get 'start'
      post 'start'
      post 'question'
      post 'exam'
      get 'finish_exam'
      post 'check_descriptive_answers'
      get 'question_back_button'
    end
    member do
      get 'start'
    end
  end

  resources :descriptives
  match '/admin/questions/choices' =>  'admin/questions#questions_choices',  :via => 'post', :as => :admin_question_type_choices

end

app/controllers/quizzes_controller.rb
class QuizzesController < ApplicationController
	before_filter :authenticate_user!
	def index
		@categories = Category.all
	end
	def new
		@questions = Question.all
		@quiz = Quiz.new
	end
	# def create
	# 	@quiz = Quiz.new(params[:quiz])
	# 	if @quiz.save
	# 		redirect_to quizzes_path
	# 	else
	# 		render 'new'
	# 	end
	# end
	def start
		# @quiz = Quiz.new
		session.delete(:user_answers)
		@category = Category.find(params[:category_id])
		@question = @category.questions
		total = @question.count.to_i
		all_question = @category.questions
		session[:questions] = all_question.sort_by{rand}[0..(total-1)]
		session[:total] = total
		session[:current] = 0
		# session[:correct] = 0
		redirect_to question_quizzes_path(:category_id => @category.id)
	end

	def question
		if params[:commit] == "Continue" || params[:commit] == "Finish"
			if session[:current] == 0
				session.delete(:user_answers)
			end
			@category = Category.find(params[:category_id])
			@question = @category.questions
			@current = session[:current] + 1
			session[:current] = @current
			@total = session[:total]
			### Initializing hash ###
			hash = {}
			@q = Question.find(params[:question_id])
			######Checking option type and send answer in params#######
			if @q.option_type == 0
				hash[params[:question_id]] = params[:answers]
			elsif @q.option_type == 1
				hash[params[:question_id]]= params[:answer_a], params[:answer_b], params[:answer_c], params[:answer_d]
			else
				hash[params[:question_id]] = params[:create_answer]
			end
			######################################
			### merging hash into exising hash ###
			######################################
			if session[:user_answers].nil?
				session[:user_answers]={}
				session[:user_answers].store(params[:question_id],hash)
			else
				session[:user_answers].store(params[:question_id],hash)
			end
			################################################
			## Checking condition for displaying questions ##
			################################################
			if @current >= @total
				redirect_to finish_quizzes_path(:category_id => @category.id, :question_id => @q.id)
			else
				@question = Question.find(session[:questions][@current])
				@answer = @question.answer
			end
			@descriptive_value = session[:user_answers]
			@descriptive_value.each do |key, value|
				question = Question.find_by_id(key)
				@current = session[:current]
				if question.option_type == 0 && params[:commit] == "Continue"
			    @user_answer = value[key]
			  elsif question.option_type == 1 && params[:commit] == "Continue" || params[:commit] == "Finish"
			  	@user_answer = value[key]
			  	@ds_value1 = @user_answer.first
			  	@ds_value2 = @user_answer.second
			  	@ds_value3 = @user_answer.third
			  	@ds_value4 = @user_answer.fourth
			  else
			  	@user_answer = value[key]
			  end
			end
		elsif params[:commit] == "Back"
			@category = Category.find(params[:category_id])
			@question = @category.questions
			@current = session[:current] - 1
			if @current == 0
				session.delete(:user_answers)
			end
			session[:current] = @current
			@total = session[:total]
			if @current >= @total
				redirect_to finish_quizzes_path
			end
			@question = Question.find(session[:questions][@current])
			@answer = @question.answer
			unless session[:user_answers].nil?
				@descriptive_value = session[:user_answers]
				@descriptive_value.each do |key, value|
					question = Question.find_by_id(key)
					if question.option_type == 0
				    @user_answer = value[key]
				  elsif question.option_type == 1
				  	@user_answer = value[key]
				  	@ds_value1 = @user_answer.first
				  	@ds_value2 = @user_answer.second
				  	@ds_value3 = @user_answer.third
				  	@ds_value4 = @user_answer.fourth
				  else
				  	@user_answer = value[key]
				  end
				end
			end
		else
			@quiz = Quiz.new
			@category = Category.find(params[:category_id])
			@question = @category.questions
			if session[:current] == 0
				session.delete(:user_answers)
			end
			@current = session[:current]
			@total = session[:total]
			if @current >= @total
				redirect_to finish_quizzes_path
			end
			@question = Question.find(session[:questions][@current])
			@answer = @question.answer
			session[:question] = @question
			session[:answer] = @answer
		end
	end
	def exam
		@questions = Question.all
		@current = session[:current] + 1
		@question = Question.find(session[:questions][@current])
		@total = session[:total]
		examid = params[:exam]
	end
	def finish
		@correct = session[:correct]
		@total = session[:total]
		@quiz = Quiz.new(:category_id => params[:category_id],
										 :user_id => current_user.id,
										 :correct_answers => find_correct_answers(session[:user_answers])
										)
		if @quiz.save
			@quiz.create_descriptive_answers(session[:user_answers])
			session.delete(:user_answers)
			redirect_to finish_exam_quizzes_path
		end
	end
	def finish_exam
		
	end

	# def question_back_button
	# 	@category = Category.find(params[:category_id])
	# 	@question = @category.questions
	# 	@current = session[:current] - 1
	# 	session[:current] = @current
	# 	@total = session[:total]
	# 	if @current >= @total
	# 		redirect_to finish_quizzes_path
	# 	end
	# 	@question = Question.find(session[:questions][@current])
	# 	respond_to do |format|
	# 		format.js
	# 	end
	# end

	private
	def find_correct_answers(user_answers)
		count = 0
		# ua = user_answers.values
		user_answers.each do |key, value|
			question = Question.find_by_id(key)
			user_answer = value[key]
			if question.option_type == 0
				actual_answer = question.answer.right_answer
			elsif question.option_type == 1
				actual_answer = question.answer.right_choices.reject(&:empty?)
			end
			actual_answer == user_answer ? (count += 1) : count
		end
		return count
	end
end

app/views/quizzes/_back_attempted_question.html.haml
.quiz_start
  .container.quiz
    .question_form
      %h1
        Question #{@current + 1} of #{@total}
      %p#question= #@question.name.html_safe
      .pull-right.time-left
        %span Time left
        %span.label.label-success{ id: 'timer'}
      = form_tag({:controller => "quizzes", :action => "question"}) do
        = @question.name.html_safe
        -if @question.option_type == 0
          %div
            = label_tag :A
            = radio_button_tag :answers, 'A'
            = @question.answer.A
          %br
          %div
            = label_tag :B
            = radio_button_tag :answers, 'B'
            = @question.answer.B
          %br
          %div
            = label_tag :C
            = radio_button_tag :answers, 'C'
            = @question.answer.C
          %br
          %div
            = label_tag :D
            = radio_button_tag :answers, 'D'
            = @question.answer.D
        - elsif @question.option_type == 1
          %div
            = label_tag :A
            = check_box_tag :answer_a, 'A'
            = @question.answer.A
          %br
          %div
            = label_tag :B
            = check_box_tag :answer_b, 'B'
            = @question.answer.B
          %br
          %div
            = label_tag :C
            = check_box_tag :answer_c, 'C'
            = @question.answer.C
          %br
          %div
            = label_tag :D
            = check_box_tag :answer_d, 'D'
            = @question.answer.D
        - else
          %div
            = label_tag :write_answer
            = text_area_tag :create_answer
        %br
        - if @current != 0
          = link_to "back", question_back_button_quizzes_path, :id => "go_back", :remote => true
          = #submit_tag("Back", :class => "submit", :id => "go_back", :remote => true)
        -if @current + 1 == @total
          = submit_tag("Finish", :class => "submit")
        -else
          = submit_tag("Continue", :class => "submit")
        = hidden_field_tag :category_id, "#{@category.id}"
        = hidden_field_tag :question_id, "#{@question.id}"
        - content_for(:title) do
          Question #{@current + 1} of #{@total}

app/views/quizzes/_form.html.haml
.login_page
  .container
    .question_form
      = form_for @quiz do |f|
        %div
          - @questions.each_with_index do |question,index|
            - if index == 0
              = index + 1
              %h3
                Question :-
              = question.name.html_safe
              = #question.option_type
              -if question.option_type == 0
                %div
                  = f.label :A, 'A:', :style => "font-weight:bold;"
                  = f.radio_button :answer1, 'answer1', :as => :radio
                  = question.answer.A
                %br
                %div
                  = f.label :B, 'B:', :style => "font-weight:bold;"
                  = f.radio_button :answer1, 'answer1', :as => :radio
                  = question.answer.B
                %br
                %div
                  = f.label :C, 'C:', :style => "font-weight:bold;"
                  = f.radio_button :answer1, 'answer1', :as => :radio
                  = question.answer.C
                %br
                %div
                  = f.label :D, 'D:', :style => "font-weight:bold;"
                  = f.radio_button :answer1, 'answer1', :as => :radio
                  = question.answer.D
              - elsif question.option_type == 1
                %div
                  = f.label :Answer1, :style => "font-weight:bold;"
                  = f.check_box :answer1
                  = question.answer.A
                %br
                %div
                  = f.label :Answer2, :style => "font-weight:bold;"
                  = f.check_box :answer2
                  = question.answer.B
                %br
                %div
                  = f.label :Answer3, :style => "font-weight:bold;"
                  = f.check_box :answer3
                  = question.answer.C
                %br
                %div
                  = f.label :Answer4, :style => "font-weight:bold;"
                  = f.check_box :answer4
                  = question.answer.D
              - else
                %div
                  = f.label :create_answer
                  = f.text_area :create_answer, :class => "ckeditor"
        %br
        %div
          = f.submit "create"

app/views/quizzes/_set_timer.html.haml
:javascript
  $(document).ready(function(){
    var set_timer = function() {
      var quiz_duration = parseInt("60");
      var target_date = new Date();
      target_date.setMinutes(target_date.getMinutes() + quiz_duration);
      target_date.setMinutes(target_date.getMinutes());
      var minutes, seconds;
      var countdown = document.getElementById("timer");
      var time_out = quiz_duration * 60 * 1000;
      setInterval(function() {
        var current_date = new Date().getTime();
        var seconds_left = (target_date - current_date) / 1000;
        minutes = parseInt(seconds_left / 60);
        seconds = parseInt(seconds_left % 60);
        countdown.innerHTML = formatTime(minutes, seconds);
      }, 100);
      setTimeout(function() {
        var attended = $(".quiz").data('attending');
        window.location.href = '#{finish_exam_quizzes_path}'+'?attended='+attended;
      }, time_out);
    }();

    // Time format helpers
    var formatTime = function(minutes, seconds) {
      var min = parseInt(minutes),
          sec = parseInt(seconds);
      return (min > 0 ? pad(min, 2) : "00") + ":" + pad(sec, 2);
    }
    var pad = function(number, length) {
      var str = '' + number;
      while (str.length < length) {str = '0' + str;}
      return str;
    }
  });

app/views/quizzes/_single_choice.html.haml
/ %div
/   = f.label :answer1, 'Answer1:', :style => "font-weight:bold;"
/   = f.radio_button :answer1, 'answer1', :as => :radio
/   = question.answer.A
/ %br
/ %div
/   = f.label :answer2, 'Answer2:', :style => "font-weight:bold;"
/   = f.radio_button :answer2, 'answer2', :as => :radio
/   = question.answer.B
/ %br
/ %div
/   = f.label :answer3, 'Answer3:', :style => "font-weight:bold;"
/   = f.radio_button :answer3, 'answer3', :as => :radio
/   = question.answer.C
/ %br
/ %div
/   = f.label :answer4, 'Answer4:', :style => "font-weight:bold;"
/   = f.radio_button :answer4, 'answer4', :as => :radio
/   = question.answer.D

app/views/quizzes/exam.html.haml
%h1
  Question #{@current + 1} of #{@total}
%p#question= @question.name.html_safe
#feedback-choices
  - @questions.each do |question|
    / - if answer.correct
    /   %p.correct.feedback-choice
    / - elsif answer == @answer
    /   %p.incorrect.feedback-choice
    / - else
    /   %p.feedback-choice
    = question.name.html_safe
/ %p.feedback
/   - if @correct
/     Correct!
/   - else
/     Incorrect.
= form_tag({:controller => "quizzes", :action => "question"}) do
  .center
    = submit_tag("Continue", :class => "submit")
- content_for(:title) do
  Question #{@current + 1} of #{@total}

app/views/quizzes/finish.html.haml
/ %h1 Quiz Results
/ %p#question
/   You answered correctly #{@correct} out of #{@total} questions.
/ %p#score
/   = @score
/ = link_to "Take another quiz", quizzes_path
/ - content_for(:title) do
/   Quiz Results
/ .login_page
/   .container.quiz
/     .question_form
/       %h1{:style => "text-align:center;"}
/         THANKS FOR GIVING TEST
/       %h4{:style => "text-align:center;"}
/         We Will Announce Result very Soon.

app/views/quizzes/finish_exam.html.haml
.quiz_start
  .container.quiz
    .question_form
      %h1{:style => "text-align:center;"}
        THANKS FOR GIVING TEST
      %h4{:style => "text-align:center;"}
        We Will Announce Result very Soon.

app/views/quizzes/index.html.haml
.quiz_start
  .container.quiz
    .question_form
      %h1 Instructions
      %h4 Welcome in IGNIS IT SOLUTION
      %h4 Examination Instructions: Online Exams:
      %ol
        %li
          All the questions are compulsory to attempt.
        %li
          No breaks were taken during the exam.
          You can not take break during online test.
        %li
          Questions may be Single-choice/Multi-choice/Descriptive.
        %li
          Result will be mailed at your Email Id which you provided at time of Registration.
      = form_tag({:controller => "quizzes",:action => "start"}) do
        %div
          = label_tag :subject
          = select_tag :category_id,options_for_select(Category.all.collect{|p| [p.question_category, p.id]}), :prompt => "please select category",  :required => true
        %p.center
          =# select_tag(:number, options_for_select((1..10).map {|x| [x, x]}), :id => "count")
        %br
        .center
          = button_tag "Start Test", :class => "btn btn-danger"
      - content_for(:title) do
        Start Quiz

app/views/quizzes/new.html.haml
= render :partial => "form"

app/views/quizzes/question.html.haml
.quiz_start
  .container.quiz{ :'data-attending' => 'false' }
    .question_form
      %h1
        Question #{@current + 1} of #{@total}
      %p#question= #@question.name.html_safe
      .pull-right.time-left
        %span Time left
        %span.label{:id => 'timer'}
      = form_tag({:controller => "quizzes", :action => "question"}) do
        = @question.name.html_safe
        -if @question.option_type == 0
          %div
            = label_tag :A
            = radio_button_tag :answers, 'A', @user_answer == 'A' ? true : false
            = @question.answer.A
          %br
          %div
            = label_tag :B
            = radio_button_tag :answers, 'B', @user_answer == 'B' ? true : false
            = @question.answer.B
          %br
          %div
            = label_tag :C
            = radio_button_tag :answers, 'C', @user_answer == 'C' ? true : false
            = @question.answer.C
          %br
          %div
            = label_tag :D
            = radio_button_tag :answers, 'D', @user_answer == 'D' ? true : false
            = @question.answer.D
        - elsif @question.option_type == 1
          %div
            = label_tag :A
            = check_box_tag :answer_a, 'A', @ds_value1 == 'A' ? true : false
            = @question.answer.A
          %br
          %div
            = label_tag :B
            = check_box_tag :answer_b, 'B', @ds_value2 == 'B' ? true : false
            = @question.answer.B
          %br
          %div
            = label_tag :C
            = check_box_tag :answer_c, 'C', @ds_value3 == 'C' ? true : false
            = @question.answer.C
          %br
          %div
            = label_tag :D
            = check_box_tag :answer_d, 'D', @ds_value4 == 'D' ? true : false
            = @question.answer.D
        - else
          %div
            = label_tag :write_answer
            = text_area_tag :create_answer, @user_answer
            =# @var[@question.id][@question.id]
            =# @descriptive_value[@question.id][@question.id]
        %br
        - if @current != 0
          = #link_to "back", question_back_button_quizzes_path, :id => "go_back", :remote => true
          = submit_tag("Back", :class => "submit", :id => "go_back", :remote => true)
        -if @current + 1 == @total
          = submit_tag("Finish", :class => "submit")
        -else
          = submit_tag("Continue", :class => "submit")
        = hidden_field_tag :category_id, "#{@category.id}"
        = hidden_field_tag :question_id, "#{@question.id}"
        - content_for(:title) do
          Question #{@current + 1} of #{@total}

/ in file javascript moved to a partial
= render :partial => 'set_timer'
/ :javascript
/   $(document).ready(function() { 
/     $("#go_back").on('click',function(){
/       $.ajax({
/         url: "#{question_back_button_quizzes_path(:category_id => params[:category_id], :question_id => params[:question_id])}",
/         type: "get"
/       })
/     })
/   })

app/views/quizzes/question_back_button.js.haml
$("#go_back").append("#{escape_javascript( render :partial => 'back_attempted_question')}");

app/views/quizzes/start.html.haml
= hidden_field_tag :category_id, :value => params[:category_id]