config/routes.rb
OnlineTest::Application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  devise_for :users

  root :to => 'homes#index'
  resources :homes, :only => [:index]
  resources :questions do
    collection do
      get 'choices'
    end
  end
  resources :answers
  resources :categories
  resources :quizzes do
    collection do
      get 'index'
      get 'question'
      get 'finish'
      get 'start'
      post 'start'
      post 'question'
      post 'exam'
      get 'finish_exam'
      post 'check_descriptive_answers'
      get 'question_back_button'
    end
    member do
      get 'start'
    end
  end

  resources :descriptives
  match '/admin/questions/choices' =>  'admin/questions#questions_choices',  :via => 'post', :as => :admin_question_type_choices

end

app/views/layouts/_footer.html.haml
.container
  Copyright © 2014 by IGNIS IT SOLUTIONS.
  %br/
  .our_site
    All Rights Reserved.
    %a{href: "http://www.ignisitsolutions.com/"} www.ignisitsolutions.com
  %br/
  = social_share_button_tag

:css
  .our_site a {
    color : #002B00 !important;
  }

app/views/layouts/_navigation.html.haml
%div.main_header
  = link_to (image_tag "logo.png", :width => "145px;", :height => "150px;"), root_path
  = link_to "Start Test", quizzes_path, :class => "brand"
  %ul.nav.navbar-nav.pull-right
    - if user_signed_in?
      %li.user
        %span.username{style: "color:#a6d8f7;font-size:18px;margin-top:25px;display:inline-block; font-family:Verdana, Geneva, sans-serif;"}
          -if current_user.name.present?
            = current_user.name
          -else
            guest user
      %li.dropdown.user{style: "padding-top:15px;"}
        %a.dropdown-toggle{"data-close-others" => "true", "data-hover" => "dropdown", "data-toggle" => "dropdown", href: "#"}
          = image_tag "index.png", width: "20", height: "20"
        %ul.dropdown-menu
          %li
            = #link_to "My Profile", profile_path(current_user)
          %li
            = link_to 'Edit account', edit_user_registration_path
          %li
            = link_to destroy_user_session_path, :method => :delete do
              %i.fa.fa-sign-out
              Log Out
    - else
      %li
        = link_to 'Login', new_user_session_path
      %li
        = link_to 'Sign up', new_user_registration_path
  .user-view.pull-right
    .myaccount.pull-left
      .logout
        .pull-left.user-name
          Yogendra Vishwakarma
        .caret.pull-left
        .facebook-image.pull-right
          .user-icon
        .clear
        #user-menu.hidden
          .arrow-up
          .section-b
            %ul
              %li
                %a{href: "/yourorders"} Your Orders
              %li
                %a{href: "/paytmcash"} Paytm Cash
              %li
                %a{href: "/settings"} Settings
              %li
                %a{href: "/help"} Help & Support
              %li
                %a{href: "/logout"} Sign Out

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Online Test Module
    = stylesheet_link_tag    "application", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
  %body
    %nav#nav.navbar.navbar-default.affix-top{role: "navigation"}
      %nav.navbar-inner
        .container
          = render 'layouts/navigation'
    = yield
  #footer
    = render 'layouts/footer'